Ripple modules
3xplcom/Core pull request #55
Opened 2023-10-23 19:20 UTC by jzethar

This PR contains modules for Ripple blockchain: main module, NFT and token modules

2023-11-28 22:22 UTC, Har01d commented
The main module is being tested now: https://3xpl.com/xrp-ledger

2024-02-23 07:40 UTC, alexqrid requested changes
Need some minor style and logic (extra `else`) fixes

2024-02-23 07:40 UTC, alexqrid commented on Modules/Common/RippleLikeFTModule.php
> +                            } else {
@jzethar fully comment this useless else please

2024-02-23 07:40 UTC, alexqrid commented on Modules/Common/RippleLikeFTModule.php
> +                                        } else {
same as previous else, have to be commented.

2024-02-23 07:40 UTC, alexqrid commented on Modules/Common/RippleLikeFTModule.php
> +                                            } else {
comment

2024-02-23 07:40 UTC, alexqrid commented on Modules/Common/RippleLikeFTModule.php
> +                                            } else {
comment

2024-02-23 07:40 UTC, alexqrid commented on Modules/Common/RippleTraits.php
> +}
add new line to the end of file please

2024-02-23 07:40 UTC, alexqrid commented on Modules/RippleMainModule.php
> +}
no new line

2024-04-18 18:49 UTC, Har01d commented
Merging this despite it does not support the latest transaction types (the recent XRPL upgrade).

2024-04-18 18:49 UTC, Har01d approved these changes

2024-04-18 18:50 UTC, merged