Add .box support
3xplcom/Core pull request #76
Opened 2024-01-24 16:59 UTC by Har01d

.box is a domain zone which is routable in both Web2 and Web3. See my.box for details.

2024-01-24 17:24 UTC, Har01d commented
The integration is live: https://3xpl.com/search?q=glo.box

2024-01-24 17:27 UTC, alexqrid requested changes
https://3xpl.com/search?q=ohms.box
returns 0x000000000000000000000000000000000000 address for non-existent domains

2024-01-24 17:27 UTC, alexqrid approved these changes

2024-01-24 17:51 UTC, Har01d commented
Yes, `ENS Forward Resolution` should be set up at my.box for the domain to be visible with the resolver.

2024-01-26 19:13 UTC, alexqrid commented on Modules/OptimismMainModule.php
> +                $address = $this->ens_get_data_from_resolver('0xBB7B805B257d7C76CA9435B3ffe780355E4C4B17', $hash, '0x6352211e', -40);
@Har01d This resolves domains that didn't setup `ENS Forward Resolution`
As domain's NFT ID is derived from the ENS `namehash` of the domain, we can get the owner of the NFT and the address we get is the resolution of the domain.
I've checked a bunch of domains and didn't found the exception from this rule.

If there's a possibility to set the resolution address different from NFT receiver address, this should be done ENS way, and our first call to the resolver address wouldn't be there.
I believe we should keep this approach to resolve domains without `ENS Forward Resolution`

2024-01-28 21:16 UTC, merged